apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jwt-secret-reader-role
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key-secret
  namespace: fybrik-blueprints
type: Opaque
data:
  JWT_KEY: "dGVtcA=="
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-key-secret
  namespace: fogprotect
type: Opaque
data:
  JWT_KEY: "dGVtcA=="
