apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: rest-read
  namespace: fogprotect
spec:
  selector:
   workloadSelector:
     matchLabels: {
       app: factory-gui
     }
  appInfo:
    purpose: security
    role: Data Owner
  data:
    - dataSetID: "fogprotect/api.control.start-robot"
      requirements:
        interface:
          protocol: s3
          dataformat: csv
