apiVersion: v1
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jwt-secret-reader-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: jwt-reader
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: jwt-secret-reader-role
  apiGroup: ""

